// Package defsInternalLUorder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package defsInternalLUorder

// Defines values for OrderResolution.
const (
	OrderResolutionCancelledByClient  OrderResolution = "cancelled_by_client"
	OrderResolutionCancelledByService OrderResolution = "cancelled_by_service"
	OrderResolutionPaid               OrderResolution = "paid"
)

// Defines values for OrderStatus.
const (
	OrderStatusCancelledByClient  OrderStatus = "cancelled_by_client"
	OrderStatusCancelledByService OrderStatus = "cancelled_by_service"
	OrderStatusNew                OrderStatus = "new"
	OrderStatusPaid               OrderStatus = "paid"
	OrderStatusServing            OrderStatus = "serving"
)

// OrderResolution defines model for OrderResolution.
type OrderResolution string

// OrderStatus defines model for OrderStatus.
type OrderStatus string
