openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления рестораном.

paths:
    /admin/v1/restaurant/create:
        post:
            summary: Создание ресторана
            description: Создание ресторана
            security:
                - CookieAuth: []
            parameters:
                - $ref: '#/components/parameters/user_uuid'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1RestaurantCreateRequest'
            responses:
                '200':
                    description: Успешное создание ресторана
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1RestaurantCreateResponse'
                '401':
                    description: Ошибка создания ресторана, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: Ошибка создания ресторана, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка создания ресторана, пользователь не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /admin/v1/restaurant/list:
        get:
            summary: Получение списка ресторанов пользователя
            description: Получение списка ресторанов пользователя
            security:
                - CookieAuth: []
            parameters:
                - $ref: '#/components/parameters/user_uuid'
            responses:
                '200':
                    description: Список ресторанов пользователя
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1RestaurantListResponse'
                '401':
                    description: Ошибка получения списка ресторанов, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка получения списка ресторанов, пользователь не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    securitySchemes:
        CookieAuth:
            name: jwt
            type: apiKey
            in: cookie
        
    parameters:
        user_uuid:
            in: header
            name: User-UUID
            description: Уникальный идентификатор пользователя
            required: true
            schema:
                type: string
                format: uuid

    schemas:
        # /admin/v1/restaurant/create_POST
        AdminV1RestaurantCreateRequest:
            type: object
            additionalProperties: false
            properties:
                restaurant_name:
                    $ref: '#/components/schemas/RestaurantName'
            required:
                - restaurant_name

        AdminV1RestaurantCreateResponse:
            type: object
            additionalProperties: false
            properties:
                restaurant_uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
            required:
                - restaurant_uuid

        # /admin/v1/restaurant/list_GET
        AdminV1RestaurantListResponse:
            type: object
            additionalProperties: false
            properties:
                restaurant_list:
                    type: array
                    items:
                        $ref: '#/components/schemas/Restaurant'
            required:
                - restaurant_list

        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum: 
                        - not_authorized
                        - already_exist
                        - user_not_found
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        # Objects
        Restaurant:
            type: object
            additionalProperties: false
            properties:
                uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
                name:
                    $ref: '#/components/schemas/RestaurantName'
            required:
                - uuid
                - name

        RestaurantUUID:
            type: string
            format: uuid
            description: Уникальный идентификатор ресторана
        
        RestaurantName:
            type: string
            description: Назавние ресторана на латинице
            minLength: 1
            maxLength: 50
            pattern: "^[A-Za-z0-9 \\-]+$"