openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления пользователем.

paths:
    /admin/v1/user/sign-up:
        post:
            summary: Регистрация пользователя в админке
            description: Регистрирует пользователя в админке
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1UserSignUpRequest'
            responses:
                '200':
                    description: Успешная регистрация и авторизация
                    headers:
                        Set-Cookie:
                            description: JWT токен
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UserSignUpResponse'
                '409':
                    description: Ошибка регистрации, пользователь уже существует
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UserSignUp409ErrorResponse'

    /admin/v1/user/sign-in:
        post:
            summary: Авторизация пользователя в админке
            description: Авторизует пользователя в админке
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1UserSignInRequest'
            responses:
                '200':
                    description: Успешная авторизация
                    headers:
                        Set-Cookie:
                            description: JWT токен
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UserSignInResponse'
                '403':
                    description: Ошибка авторизации, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UserSignIn403ErrorResponse'

components:
    schemas:
        # /admin/v1/user/sign-up_POST
        AdminV1UserSignUpRequest:
            type: object
            additionalProperties: false
            properties:
                login:
                    description: Логин пользователя, используемый для входа
                    $ref: '#/components/schemas/Login'
                tg_login:
                    description: Логин пользователя в Telegram
                    $ref: '#/components/schemas/Login'
                first_name:
                    type: string
                    description: Имя пользователя на латинице
                    minLength: 1
                    maxLength: 50
                    pattern: "^[A-Za-z \\-]+$"
                last_name:
                    type: string
                    description: Фамилия пользователя на латинице
                    minLength: 1
                    maxLength: 50
                    pattern: "^[A-Za-z \\-]+$"
                password: 
                    $ref: '#/components/schemas/Password'
            required:
                - login
                - tg_login
                - first_name
                - last_name
                - password

        AdminV1UserSignUpResponse:
            type: object
            additionalProperties: false
            properties:
                user_uuid:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор пользователя
            required:
                - user_uuid

        AdminV1UserSignUp409ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum: 
                        - already_exist
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        # /admin/v1/user/sign-in_POST
        AdminV1UserSignInRequest:
            type: object
            additionalProperties: false
            properties:
                login:
                    description: Логин пользователя, используемый для входа
                    $ref: '#/components/schemas/Login'
                password:
                    $ref: '#/components/schemas/Password'
            required:
                - login
                - password

        AdminV1UserSignInResponse:
            type: object
            additionalProperties: false
            properties:
                user_uuid:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор пользователя
            required:
                - user_uuid

        AdminV1UserSignIn403ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum: 
                        - not_found
                        - incorrect_password
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        Login:
            type: string
            description: Логин пользователя
            pattern: "^[a-zA-Z][a-zA-Z0-9_]{4,31}$"
            minLength: 4
            maxLength: 31

        Password:
            type: string
            description: Пароль пользователя
            minLength: 8
            maxLength: 24
            pattern: "^[A-Za-z0-9!@#\\$\\^%&*()_+=\\-]+$"
