openapi: 3.0.3
info:
    title: SmartTable Admin API
    version: 1.0.0
    description: API для управления рестораном.

paths:
    /admin/v1/restaurant/create:
        post:
            summary: Создание ресторана
            description: Создание ресторана
            parameters:
                - $ref: '#/components/parameters/user_uuid'
                - $ref: '#/components/parameters/jwt_token'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1RestaurantCreateRequest'
            responses:
                '200':
                    description: Успешное создание ресторана
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1RestaurantCreateResponse'
                '401':
                    description: Ошибка создания ресторана, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: Ошибка создания ресторана, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка создания ресторана, пользователь не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /admin/v1/restaurant/list:
        get:
            summary: Получение списка ресторанов пользователя
            description: Получение списка ресторанов пользователя
            parameters:
                - $ref: '#/components/parameters/user_uuid'
                - $ref: '#/components/parameters/jwt_token'
            responses:
                '200':
                    description: Список ресторанов пользователя
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1RestaurantListResponse'
                '401':
                    description: Ошибка получения списка ресторанов, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка получения списка ресторанов, пользователь не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /admin/v1/restaurant/dish/create:
        post:
            summary: Создание блюда ресторана
            description: Создание блюда ресторана
            parameters:
                - $ref: '#/components/parameters/user_uuid'
                - $ref: '#/components/parameters/jwt_token'
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            $ref: '#/components/schemas/AdminV1RestaurantDishCreateRequest'
                        encoding:
                            dish_picture_file:
                                contentType: image/png
            responses:
                '200':
                    description: ID созданного блюда
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1RestaurantDishCreateResponse'
                '400':
                    description: Некорректный запрос создания
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '401':
                    description: Ошибка создания, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: Ошибка создания, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка создания, пользователь не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    parameters:
        user_uuid:
            in: header
            name: User-UUID
            description: Уникальный идентификатор пользователя
            required: true
            schema:
                type: string
                format: uuid

        jwt_token:
            in: header
            name: JWT-Token
            description: jwt токен пользователя
            required: true
            schema:
                type: string

    schemas:
        # /admin/v1/restaurant/create_POST
        AdminV1RestaurantCreateRequest:
            type: object
            additionalProperties: false
            properties:
                restaurant_name:
                    $ref: '#/components/schemas/RestaurantName'
            required:
                - restaurant_name

        AdminV1RestaurantCreateResponse:
            type: object
            additionalProperties: false
            properties:
                restaurant_uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
            required:
                - restaurant_uuid

        # /admin/v1/restaurant/list_GET
        AdminV1RestaurantListResponse:
            type: object
            additionalProperties: false
            properties:
                restaurant_list:
                    type: array
                    items:
                        $ref: '#/components/schemas/RestaurantInfo'
            required:
                - restaurant_list

        # /admin/v1/restaurant/dish/create_POST
        AdminV1RestaurantDishCreateRequest:
            type: object
            additionalProperties: false
            properties:
                restaurant_uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
                dish_name:
                    type: string
                description:
                    type: string
                category:
                    type: string
                calories:
                    type: integer
                    minimum: 0
                weight:
                    type: integer
                    minimum: 0
                dish_picture_file:
                    type: string
                    format: binary
            required:
                - restaurant_uuid
                - dish_name
                - description
                - category
                - calories
                - weight
                - dish_picture_file

        AdminV1RestaurantDishCreateResponse:
            type: object
            additionalProperties: false
            properties:
                dish_uuid:
                    type: string
                    format: uuid
            required:
                - dish_uuid

        # Errors
        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum: 
                        - not_authorized
                        - already_exist
                        - user_not_found
                        - invalid_request
                        - restaurant_not_found
                        - access_denied
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        # Objects
        RestaurantInfo:
            type: object
            additionalProperties: false
            properties:
                uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
                name:
                    $ref: '#/components/schemas/RestaurantName'
            required:
                - uuid
                - name

        RestaurantUUID:
            type: string
            format: uuid
            description: Уникальный идентификатор ресторана
        
        RestaurantName:
            type: string
            description: Назавние ресторана на латинице
            minLength: 1
            maxLength: 50
            pattern: "^[A-Za-z0-9 \\-]+$"