openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления плейсом.

paths:
    /admin/v1/place/create:
        post:
            summary: Создание плейса
            description: Создание плейса
            security:
                - CookieAuth: []
            parameters:
                - $ref: '#/components/parameters/user_uuid'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1PlaceCreateRequest'
            responses:
                '200':
                    description: Успешное создание плейса
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1PlaceCreateResponse'
                '400':
                    description: Ошибка создания плейса, некорректный формат данных
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'              
                '401':
                    description: Ошибка создания плейса, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: Ошибка создания плейса, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка создания плейса, пользователь или ресторан не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /admin/v1/place/list:
        post:
            summary: Получение списка плейсов пользователя
            description: Получение списка плейсов пользователя
            security:
                - CookieAuth: []
            parameters:
                - $ref: '#/components/parameters/user_uuid'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1PlaceListRequest'
            responses:
                '200':
                    description: Список плейсов ресторана
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1PlaceListResponse'
                '400':
                    description: Ошибка получения списка плейсов ресторана, некорректный формат данных
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'              
                '401':
                    description: Ошибка получения списка плейсов ресторана, пользователь не авторизован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '403':
                    description: Ошибка получения списка плейсов ресторана, отказано в доступе, некорретные данные
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка получения списка плейсов ресторана, пользователь или ресторан не найден
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    securitySchemes:
        CookieAuth:
            name: jwt
            type: apiKey
            in: cookie
        
    parameters:
        user_uuid:
            in: header
            name: User-UUID
            description: Уникальный идентификатор пользователя
            required: true
            schema:
                type: string
                format: uuid

    schemas:
        # /admin/v1/place/create_POST
        AdminV1PlaceCreateRequest:
            type: object
            additionalProperties: false
            properties:
                restaurant_uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
                address:
                    $ref: '#/components/schemas/Address'
                table_count:
                    $ref: '#/components/schemas/TableCount'
                opening_time:
                    $ref: '#/components/schemas/Time'
                closing_time:
                    $ref: '#/components/schemas/Time'
            required:
                - restaurant_uuid
                - address
                - table_count
                - opening_time
                - closing_time

        AdminV1PlaceCreateResponse:
            type: object
            additionalProperties: false
            properties:
                place_uuid:
                    $ref: '#/components/schemas/PlaceUUID'
            required:
                - place_uuid

        # /admin/v1/place/list_POST
        AdminV1PlaceListRequest:
            type: object
            additionalProperties: false
            properties:
                restaurant_uuid:
                    $ref: '#/components/schemas/RestaurantUUID'
            required:
                - restaurant_uuid

        AdminV1PlaceListResponse:
            type: object
            additionalProperties: false
            properties:
                place_list:
                    type: array
                    items:
                        $ref: '#/components/schemas/PlaceInfo'
            required:
                - place_list

        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum: 
                        - incorrect_time_format
                        - incorrect_table_count
                        - not_authorized
                        - already_exist
                        - access_denied
                        - user_not_found
                        - restaurant_not_found
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        # Objects
        PlaceInfo:
            type: object
            additionalProperties: false
            properties:
                uuid:
                    $ref: '#/components/schemas/PlaceUUID'
                address:
                    $ref: '#/components/schemas/Address'
                table_count:
                    $ref: '#/components/schemas/TableCount'
                opening_time:
                    $ref: '#/components/schemas/Time'
                closing_time:
                    $ref: '#/components/schemas/Time'
            required:
                - uuid
                - address
                - table_count
                - opening_time
                - closing_time

        RestaurantUUID:
            type: string
            format: uuid
            description: Уникальный идентификатор ресторана

        PlaceUUID:
            type: string
            format: uuid
            description: Уникальный идентификатор плейса
        
        Address:
            type: string
            minLength: 1
            maxLength: 50
            pattern: "^[A-Za-z0-9 \\-]+$"
        
        TableCount:
            type: integer
            minimum: 0
            exclusiveMinimum: true

        Time:
            type: string
            pattern: '^([01][0-9]|2[0-3]):[0-5][0-9]$'
