openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления заказами.

paths:
    /customer/v1/order/create:
        post:
            summary: Создание заказа, если первый пользователь в группе, иначе присоединение к заказу.
            description: Создаёт новый заказ
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CustomerV1OrderCreateRequest'

            responses:
                '200':
                    description: Заказ успешно создан
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomerV1OrderCreateResponse'

                '403':
                    description: Ошибка авторизации или доступа
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    schemas:
        CustomerV1OrderCreateRequest:
            type: object
            additionalProperties: false
            properties:
                table_id:
                    type: string
                    description: Уникальный идентификатор стола
                room_code:
                    type: string
                    description: Код комнаты для группового заказа
                customer_uuid:
                    type: string
                    format: uuid
                    description: Логин пользователя в Telegram
            required:
                - table_id
                - customer_uuid

        CustomerV1OrderCreateResponse:
            type: object
            additionalProperties: false
            properties:
                order_uuid:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор созданного заказа
            required:
                - order_uuid

        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum:
                        - invalid_room_code
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message
