openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления заказами.

paths:
    /customer/v1/sign-in:
        post:
            summary: Авторизация пользователя в приложении
            description: Авторизует пользователя
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CustomerV1OrderCustomerSignInRequest'
            responses:
                '200':
                    description: Авторизирован
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomerV1OrderCustomerSignInResponse'
                '403':
                    description: Некорректные данные запроса
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Не найден пользователь
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
components:
    schemas:
        CustomerV1OrderCustomerSignInRequest:
            type: object
            additionalProperties: false
            properties:
                init_data:
                    type: string
                tg_id:
                    type: string
                tg_login:
                    $ref: '#/components/schemas/Login'
            required:
                - init_data
                - tg_id
                - tg_login

        CustomerV1OrderCustomerSignInResponse:
            type: object
            additionalProperties: false
            properties:
                customer_uuid:
                    type: string
                    format: uuid
                jwt_token:
                    type: string
            required:
                - customer_uuid
                - jwt_token

        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum:
                        - not_found
                        - incorrect_init_data
                        - already_exist
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message

        Login:
            type: string
            description: Логин пользователя
            pattern: "^[a-zA-Z][a-zA-Z0-9_]{4,31}$"
            minLength: 4
            maxLength: 31
