openapi: 3.0.3
info:
    title: SmartTable Mobile API
    version: 1.0.0
    description: API для управления заказами.

paths:
    /customer/v1/order/create:
        post:
            summary: Создаёт новый заказ
            description: Создание заказа, если первый пользователь в группе, иначе присоединение к заказу.
            parameters:
                - $ref: '#/components/parameters/CustomerUUID'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CustomerV1OrderCreateRequest'
            responses:
                '200':
                    description: Заказ успешно создан
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomerV1OrderCreateResponse'

                '403':
                    description: Ошибка авторизации или доступа
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

    /customer/v1/order/catalog:
        get:
            summary: Получение каталога
            description: Отображение каталога плейса
            parameters:
                - $ref: '#/components/parameters/CustomerUUID'
                - $ref: '#/components/parameters/OrderUUID'
            responses:
                '200':
                    description: Список блюд (JSON + binary images)
                    content:
                        multipart/mixed:
                            schema:
                                type: string
                                format: binary
                '403':
                    description: Ошибка авторизации или доступа
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '404':
                    description: Ошибка поиска заказа или клиента
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

components:
    parameters:
        CustomerUUID:
            in: header
            name: Customer-UUID
            description: Уникальный идентификатор пользователя
            required: true
            schema:
                type: string
                format: uuid

        OrderUUID:
            in: header
            name: Order-UUID
            description: Уникальный идентификатор заказа
            required: true
            schema:
                type: string
                format: uuid

    schemas:
        CustomerV1OrderCreateRequest:
            type: object
            additionalProperties: false
            properties:
                table_id:
                    type: string
                    description: Уникальный идентификатор стола
                room_code:
                    type: string
                    description: Код комнаты для группового заказа
            required:
                - table_id

        CustomerV1OrderCreateResponse:
            type: object
            additionalProperties: false
            properties:
                order_uuid:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор созданного заказа
            required:
                - order_uuid

        Catalog:
            type: object
            additionalProperties: false
            properties:
                room_code:
                    type: string
                total_price:
                    type: string
                menu:
                    type: array
                    items:
                        $ref: '#/components/schemas/MenuDishItem'
            required:
                - room_code
                - total_price
                - menu

        MenuDishItem:
            type: object
            additionalProperties: false
            properties:
                id:
                    type: string
                    format: uuid
                price:
                    type: string
                name:
                    type: string
                calories:
                    type: integer
                    minimum: 0
                count:
                    type: integer
                    minimum: 0
            required:
                - id
                - price
                - name
                - calories
                - count

        ErrorResponse:
            type: object
            additionalProperties: false
            properties:
                code:
                    type: string
                    description: Код ошибки
                    enum:
                        - invalid_room_code
                        - invalid_table_id
                        - already_exist
                        - order_not_found
                        - customer_not_found
                        - access_denied
                message:
                    type: string
                    description: Описание ошибки
            required:
                - code
                - message
