// Package defs_internal_admin_user_db provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package defs_internal_admin_user_db

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Login Логин пользователя
type Login = string

// PgUser defines model for PgUser.
type PgUser struct {
	ChatID    string    `json:"chat_id"`
	CreatedAt time.Time `json:"created_at"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`

	// Login Логин пользователя
	Login        Login  `json:"login"`
	PasswordHash string `json:"password_hash"`
	TgID         string `json:"tg_id"`

	// TgLogin Логин пользователя
	TgLogin   Login              `json:"tg_login"`
	UpdatedAt time.Time          `json:"updated_at"`
	UUID      openapi_types.UUID `json:"uuid"`
}
