// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: fetch_customer_by_uuid.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const fetchCustomer = `-- name: FetchCustomer :one

SELECT
    to_jsonb(c)
FROM
    smart_table_customer.customers c
WHERE
    uuid = $1::UUID
`

// args:
// $1 - UUID
func (q *Queries) FetchCustomer(ctx context.Context, dollar_1 uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, fetchCustomer, dollar_1)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}
