// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SmartTableCustomer struct {
	Uuid       uuid.UUID
	TgID       string
	TgLogin    string
	AvatarLink string
	ChatID     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SmartTableDish struct {
	Uuid        uuid.UUID
	Name        string
	Description string
	Weight      int32
	PictureLink string
	RestUuid    uuid.UUID
	Category    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SmartTableItem struct {
	Uuid         uuid.UUID
	OrderUuid    uuid.UUID
	Comment      pgtype.Text
	Status       string
	Resolution   pgtype.Text
	Name         string
	Description  string
	PictureLink  string
	Weight       int32
	Category     string
	Price        pgtype.Numeric
	CustomerUuid uuid.UUID
	DishUuid     uuid.UUID
	IsDraft      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SmartTableMenuDish struct {
	Uuid      uuid.UUID
	DishUuid  uuid.UUID
	PlaceUuid uuid.UUID
	Price     pgtype.Numeric
	Exist     bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SmartTableOrder struct {
	Uuid          uuid.UUID
	RoomCode      string
	TableID       string
	CustomersUuid []uuid.UUID
	HostUserUuid  uuid.UUID
	Status        string
	Resolution    pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type SmartTablePlace struct {
	Uuid        uuid.UUID
	RestUuid    uuid.UUID
	Address     string
	OpeningTime pgtype.Time
	ClosingTime pgtype.Time
	TableCount  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SmartTableRestaurant struct {
	Uuid      uuid.UUID
	Name      string
	OwnerUuid uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SmartTableStaff struct {
	UserUuid  uuid.UUID
	PlaceUuid uuid.UUID
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SmartTableUser struct {
	Uuid         uuid.UUID
	AvatarLink   string
	Login        string
	TgLogin      string
	Name         string
	Phone        string
	PasswordHash string
	ChatID       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
