app:
    port: 8080
    env: production
    admin:
        jwt:
            enable: true
            secret_key: APP_ADMIN_JWT_SECRET_KEY
            expiration: 24h
    customer:
        jwt:
            enable: true
            secret_key: APP_CUSTOMER_JWT_SECRET_KEY
            expiration: 24h
        init_data:
            expiration: 24h
    cors:
        allow_origins: 
            - http://localhost:3002
            - http://localhost:3000
            - http://localhost:3001
            - http://localhost:3003
            - https://h91q6lp9-3000.euw.devtunnels.ms
        allow_methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        allow_headers:
            - ngrok-skip-browser-warning
            - Authorization
            - User-UUID
            - Customer-UUID
            - Order-UUID
            - JWT-Token
            - content-type
        allow_credentials: true
    max_input_file_size_mb: 1000

database:
    host: smart-table-db
    port: 5432
    user: DATABASE_USER
    password: DATABASE_PASSWORD
    name: DATABASE_NAME
    timeout: 5s
    max_connections: 60
    min_connections: 10
    max_connection_lifetime: 1h
    max_connection_idle_time: 10m
    health_check_period: 5m
    max_connection_lifetime_jitter: 1m

logging:
    level: info
    format: json
    file: logs/app.log
    max_size: 100
    max_backups: 5
    max_age: 30
    compress: true
    enable_console_and_file: true
    server:
        request_sym_limit: 1000
        response_sym_limit: 1000
    bot:
        enable: false

bot:
    token: BOT_TOKEN
    poller_timeout: 10s
    web_app_url: https://t.me/UpdateEventBot?startapp
    test_mode: false

s3:
    access_key: S3_ACCESS_KEY
    secret_key: S3_SECRET_KEY
    endpoint: storage.yandexcloud.net
    region: ru-central1
    bucket: smart-table
