app:
    port: 8080
    env: development

database:
    host: localhost
    port: 5432
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    name: smart-table
    timeout: 5s
    max_connections: 50
    min_connections: 5
    max_connection_lifetime: 30m
    max_connection_idle_time: 10m
    health_check_period: 5m
    max_connection_lifetime_jitter: 1m

logging:
    level: debug
    format: json
    file: logs/app.log
    max_size: 10
    max_backups: 3
    max_age: 30
    compress: true
    enable_console_and_file: true
