// Package defs_internal_customer_db provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package defs_internal_customer_db

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PgCustomer defines model for PgCustomer.
type PgCustomer struct {
	AvatarLink string             `json:"avatar_link"`
	ChatID     string             `json:"chat_id"`
	CreatedAt  time.Time          `json:"created_at"`
	TgID       string             `json:"tg_id"`
	TgLogin    string             `json:"tg_login"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UUID       openapi_types.UUID `json:"uuid"`
}
