/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CustomerV1OrderCreateRequest from '../model/CustomerV1OrderCreateRequest';
import CustomerV1OrderCreateResponse from '../model/CustomerV1OrderCreateResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the customerV1OrderCreatePost operation.
     * @callback module:api/DefaultApi~customerV1OrderCreatePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CustomerV1OrderCreateResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Создание заказа, если первый пользователь в группе, иначе присоединение к заказу.
     * Создаёт новый заказ
     * @param {module:model/CustomerV1OrderCreateRequest} customerV1OrderCreateRequest 
     * @param {module:api/DefaultApi~customerV1OrderCreatePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CustomerV1OrderCreateResponse}
     */
    customerV1OrderCreatePost(customerV1OrderCreateRequest, callback) {
      let postBody = customerV1OrderCreateRequest;
      // verify the required parameter 'customerV1OrderCreateRequest' is set
      if (customerV1OrderCreateRequest === undefined || customerV1OrderCreateRequest === null) {
        throw new Error("Missing the required parameter 'customerV1OrderCreateRequest' when calling customerV1OrderCreatePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CustomerV1OrderCreateResponse;
      return this.apiClient.callApi(
        '/customer/v1/order/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
