// Package defs_internal_order_db provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package defs_internal_order_db

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PgOrder defines model for PgOrder.
type PgOrder struct {
	CreatedAt     time.Time            `json:"created_at"`
	CustomersUUID []openapi_types.UUID `json:"customers_uuid"`
	HostUserUUID  openapi_types.UUID   `json:"host_user_uuid"`
	Resolution    *string              `json:"resolution,omitempty"`
	RoomCode      string               `json:"room_code"`
	Status        string               `json:"status"`
	TableID       string               `json:"table_id"`
	UpdatedAt     time.Time            `json:"updated_at"`
	UUID          openapi_types.UUID   `json:"uuid"`
}
