services:
    smart-table:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PROJECT_ROOT=/app
        env_file:
            - configs/config.env
            - configs/.env
        ports:
            - "${SMART_TABLE_APP_PORT}:${SMART_TABLE_APP_PORT}"
        restart: always
        volumes:
            - "./${SMART_TABLE_LOGGING_FILE}:/${SMART_TABLE_LOGGING_FILE}"
        depends_on:
            - smart-table-db

    smart-table-db:
        image: postgres:15
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${SMART_TABLE_DATABASE_PORT}:${SMART_TABLE_DATABASE_PORT}"
        restart: always
        volumes:
            - smart_table_db_data:/var/lib/postgresql/data

    liquibase:
        image: liquibase/liquibase:4.26
        depends_on:
            - smart-table-db
        volumes:
            - ./postgresql:/liquibase/changelog
        environment:
            - LIQUIBASE_LOG_LEVEL=info
        command:
            - --searchPath=/liquibase/changelog/
            - --changelog-file=changelog.xml
            - --driver=org.postgresql.Driver
            - --url=jdbc:postgresql://smart-table-db:${SMART_TABLE_DATABASE_PORT}/${DATABASE_NAME}
            - --username=${DATABASE_USER}
            - --password=${DATABASE_PASSWORD}
            - update
        restart: "no"

volumes:
    smart_table_db_data:
