// Package defsInternalLUitem provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package defsInternalLUitem

// Defines values for ItemResolution.
const (
	ItemResolutionCancelledByClient  ItemResolution = "cancelled_by_client"
	ItemResolutionCancelledByService ItemResolution = "cancelled_by_service"
	ItemResolutionPaid               ItemResolution = "paid"
)

// Defines values for ItemStatus.
const (
	ItemStatusAccepted           ItemStatus = "accepted"
	ItemStatusCancelledByClient  ItemStatus = "cancelled_by_client"
	ItemStatusCancelledByService ItemStatus = "cancelled_by_service"
	ItemStatusCooked             ItemStatus = "cooked"
	ItemStatusCooking            ItemStatus = "cooking"
	ItemStatusNew                ItemStatus = "new"
	ItemStatusPaid               ItemStatus = "paid"
	ItemStatusServed             ItemStatus = "served"
)

// ItemResolution defines model for ItemResolution.
type ItemResolution string

// ItemStatus defines model for ItemStatus.
type ItemStatus string
