/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerV1OrderCustomerSignUpRequest model module.
 * @module model/CustomerV1OrderCustomerSignUpRequest
 * @version 1.0.0
 */
class CustomerV1OrderCustomerSignUpRequest {
    /**
     * Constructs a new <code>CustomerV1OrderCustomerSignUpRequest</code>.
     * @alias module:model/CustomerV1OrderCustomerSignUpRequest
     * @param tgId {String} 
     * @param tgLogin {String} Телеграм логин пользователя
     * @param chatId {String} 
     */
    constructor(tgId, tgLogin, chatId) { 
        
        CustomerV1OrderCustomerSignUpRequest.initialize(this, tgId, tgLogin, chatId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tgId, tgLogin, chatId) { 
        obj['tg_id'] = tgId;
        obj['tg_login'] = tgLogin;
        obj['chat_id'] = chatId;
    }

    /**
     * Constructs a <code>CustomerV1OrderCustomerSignUpRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerV1OrderCustomerSignUpRequest} obj Optional instance to populate.
     * @return {module:model/CustomerV1OrderCustomerSignUpRequest} The populated <code>CustomerV1OrderCustomerSignUpRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerV1OrderCustomerSignUpRequest();

            if (data.hasOwnProperty('tg_id')) {
                obj['tg_id'] = ApiClient.convertToType(data['tg_id'], 'String');
            }
            if (data.hasOwnProperty('tg_login')) {
                obj['tg_login'] = ApiClient.convertToType(data['tg_login'], 'String');
            }
            if (data.hasOwnProperty('chat_id')) {
                obj['chat_id'] = ApiClient.convertToType(data['chat_id'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], File);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerV1OrderCustomerSignUpRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerV1OrderCustomerSignUpRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomerV1OrderCustomerSignUpRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['tg_id'] && !(typeof data['tg_id'] === 'string' || data['tg_id'] instanceof String)) {
            throw new Error("Expected the field `tg_id` to be a primitive type in the JSON string but got " + data['tg_id']);
        }
        // ensure the json data is a string
        if (data['tg_login'] && !(typeof data['tg_login'] === 'string' || data['tg_login'] instanceof String)) {
            throw new Error("Expected the field `tg_login` to be a primitive type in the JSON string but got " + data['tg_login']);
        }
        // ensure the json data is a string
        if (data['chat_id'] && !(typeof data['chat_id'] === 'string' || data['chat_id'] instanceof String)) {
            throw new Error("Expected the field `chat_id` to be a primitive type in the JSON string but got " + data['chat_id']);
        }

        return true;
    }


}

CustomerV1OrderCustomerSignUpRequest.RequiredProperties = ["tg_id", "tg_login", "chat_id"];

/**
 * @member {String} tg_id
 */
CustomerV1OrderCustomerSignUpRequest.prototype['tg_id'] = undefined;

/**
 * Телеграм логин пользователя
 * @member {String} tg_login
 */
CustomerV1OrderCustomerSignUpRequest.prototype['tg_login'] = undefined;

/**
 * @member {String} chat_id
 */
CustomerV1OrderCustomerSignUpRequest.prototype['chat_id'] = undefined;

/**
 * @member {File} avatar
 */
CustomerV1OrderCustomerSignUpRequest.prototype['avatar'] = undefined;






export default CustomerV1OrderCustomerSignUpRequest;

