/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerV1OrderCreateResponse model module.
 * @module model/CustomerV1OrderCreateResponse
 * @version 1.0.0
 */
class CustomerV1OrderCreateResponse {
    /**
     * Constructs a new <code>CustomerV1OrderCreateResponse</code>.
     * @alias module:model/CustomerV1OrderCreateResponse
     * @param orderUuid {String} Уникальный идентификатор созданного заказа
     */
    constructor(orderUuid) { 
        
        CustomerV1OrderCreateResponse.initialize(this, orderUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderUuid) { 
        obj['order_uuid'] = orderUuid;
    }

    /**
     * Constructs a <code>CustomerV1OrderCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerV1OrderCreateResponse} obj Optional instance to populate.
     * @return {module:model/CustomerV1OrderCreateResponse} The populated <code>CustomerV1OrderCreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerV1OrderCreateResponse();

            if (data.hasOwnProperty('order_uuid')) {
                obj['order_uuid'] = ApiClient.convertToType(data['order_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerV1OrderCreateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerV1OrderCreateResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomerV1OrderCreateResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['order_uuid'] && !(typeof data['order_uuid'] === 'string' || data['order_uuid'] instanceof String)) {
            throw new Error("Expected the field `order_uuid` to be a primitive type in the JSON string but got " + data['order_uuid']);
        }

        return true;
    }


}

CustomerV1OrderCreateResponse.RequiredProperties = ["order_uuid"];

/**
 * Уникальный идентификатор созданного заказа
 * @member {String} order_uuid
 */
CustomerV1OrderCreateResponse.prototype['order_uuid'] = undefined;






export default CustomerV1OrderCreateResponse;

