/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerV1OrderCreateRequest model module.
 * @module model/CustomerV1OrderCreateRequest
 * @version 1.0.0
 */
class CustomerV1OrderCreateRequest {
    /**
     * Constructs a new <code>CustomerV1OrderCreateRequest</code>.
     * @alias module:model/CustomerV1OrderCreateRequest
     * @param tableId {String} Уникальный идентификатор стола
     * @param customerUuid {String} Логин пользователя в Telegram
     */
    constructor(tableId, customerUuid) { 
        
        CustomerV1OrderCreateRequest.initialize(this, tableId, customerUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tableId, customerUuid) { 
        obj['table_id'] = tableId;
        obj['customer_uuid'] = customerUuid;
    }

    /**
     * Constructs a <code>CustomerV1OrderCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerV1OrderCreateRequest} obj Optional instance to populate.
     * @return {module:model/CustomerV1OrderCreateRequest} The populated <code>CustomerV1OrderCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerV1OrderCreateRequest();

            if (data.hasOwnProperty('table_id')) {
                obj['table_id'] = ApiClient.convertToType(data['table_id'], 'String');
            }
            if (data.hasOwnProperty('room_code')) {
                obj['room_code'] = ApiClient.convertToType(data['room_code'], 'String');
            }
            if (data.hasOwnProperty('customer_uuid')) {
                obj['customer_uuid'] = ApiClient.convertToType(data['customer_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerV1OrderCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerV1OrderCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomerV1OrderCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['table_id'] && !(typeof data['table_id'] === 'string' || data['table_id'] instanceof String)) {
            throw new Error("Expected the field `table_id` to be a primitive type in the JSON string but got " + data['table_id']);
        }
        // ensure the json data is a string
        if (data['room_code'] && !(typeof data['room_code'] === 'string' || data['room_code'] instanceof String)) {
            throw new Error("Expected the field `room_code` to be a primitive type in the JSON string but got " + data['room_code']);
        }
        // ensure the json data is a string
        if (data['customer_uuid'] && !(typeof data['customer_uuid'] === 'string' || data['customer_uuid'] instanceof String)) {
            throw new Error("Expected the field `customer_uuid` to be a primitive type in the JSON string but got " + data['customer_uuid']);
        }

        return true;
    }


}

CustomerV1OrderCreateRequest.RequiredProperties = ["table_id", "customer_uuid"];

/**
 * Уникальный идентификатор стола
 * @member {String} table_id
 */
CustomerV1OrderCreateRequest.prototype['table_id'] = undefined;

/**
 * Код комнаты для группового заказа
 * @member {String} room_code
 */
CustomerV1OrderCreateRequest.prototype['room_code'] = undefined;

/**
 * Логин пользователя в Telegram
 * @member {String} customer_uuid
 */
CustomerV1OrderCreateRequest.prototype['customer_uuid'] = undefined;






export default CustomerV1OrderCreateRequest;

