/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerV1OrderCustomerSignUpResponse model module.
 * @module model/CustomerV1OrderCustomerSignUpResponse
 * @version 1.0.0
 */
class CustomerV1OrderCustomerSignUpResponse {
    /**
     * Constructs a new <code>CustomerV1OrderCustomerSignUpResponse</code>.
     * @alias module:model/CustomerV1OrderCustomerSignUpResponse
     * @param customerUuid {String} 
     */
    constructor(customerUuid) { 
        
        CustomerV1OrderCustomerSignUpResponse.initialize(this, customerUuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customerUuid) { 
        obj['customer_uuid'] = customerUuid;
    }

    /**
     * Constructs a <code>CustomerV1OrderCustomerSignUpResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerV1OrderCustomerSignUpResponse} obj Optional instance to populate.
     * @return {module:model/CustomerV1OrderCustomerSignUpResponse} The populated <code>CustomerV1OrderCustomerSignUpResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerV1OrderCustomerSignUpResponse();

            if (data.hasOwnProperty('customer_uuid')) {
                obj['customer_uuid'] = ApiClient.convertToType(data['customer_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerV1OrderCustomerSignUpResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerV1OrderCustomerSignUpResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomerV1OrderCustomerSignUpResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['customer_uuid'] && !(typeof data['customer_uuid'] === 'string' || data['customer_uuid'] instanceof String)) {
            throw new Error("Expected the field `customer_uuid` to be a primitive type in the JSON string but got " + data['customer_uuid']);
        }

        return true;
    }


}

CustomerV1OrderCustomerSignUpResponse.RequiredProperties = ["customer_uuid"];

/**
 * @member {String} customer_uuid
 */
CustomerV1OrderCustomerSignUpResponse.prototype['customer_uuid'] = undefined;






export default CustomerV1OrderCustomerSignUpResponse;

