// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"

	viewsLUadminUuser "github.com/smart-table/src/views/codegen/admin_user"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

type ClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientInterface) EXPECT() *ClientInterface_Expecter {
	return &ClientInterface_Expecter{mock: &_m.Mock}
}

// PostAdminV1UserSignIn provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientInterface) PostAdminV1UserSignIn(ctx context.Context, body viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, reqEditors ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostAdminV1UserSignIn")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostAdminV1UserSignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAdminV1UserSignIn'
type ClientInterface_PostAdminV1UserSignIn_Call struct {
	*mock.Call
}

// PostAdminV1UserSignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - body viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody
//   - reqEditors ...viewsLUadminUuser.RequestEditorFn
func (_e *ClientInterface_Expecter) PostAdminV1UserSignIn(ctx interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostAdminV1UserSignIn_Call {
	return &ClientInterface_PostAdminV1UserSignIn_Call{Call: _e.mock.On("PostAdminV1UserSignIn",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostAdminV1UserSignIn_Call) Run(run func(ctx context.Context, body viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, reqEditors ...viewsLUadminUuser.RequestEditorFn)) *ClientInterface_PostAdminV1UserSignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viewsLUadminUuser.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(viewsLUadminUuser.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignIn_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostAdminV1UserSignIn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignIn_Call) RunAndReturn(run func(context.Context, viewsLUadminUuser.PostAdminV1UserSignInJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostAdminV1UserSignIn_Call {
	_c.Call.Return(run)
	return _c
}

// PostAdminV1UserSignInWithBody provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientInterface) PostAdminV1UserSignInWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostAdminV1UserSignInWithBody")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostAdminV1UserSignInWithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAdminV1UserSignInWithBody'
type ClientInterface_PostAdminV1UserSignInWithBody_Call struct {
	*mock.Call
}

// PostAdminV1UserSignInWithBody is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...viewsLUadminUuser.RequestEditorFn
func (_e *ClientInterface_Expecter) PostAdminV1UserSignInWithBody(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostAdminV1UserSignInWithBody_Call {
	return &ClientInterface_PostAdminV1UserSignInWithBody_Call{Call: _e.mock.On("PostAdminV1UserSignInWithBody",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostAdminV1UserSignInWithBody_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...viewsLUadminUuser.RequestEditorFn)) *ClientInterface_PostAdminV1UserSignInWithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viewsLUadminUuser.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(viewsLUadminUuser.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignInWithBody_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostAdminV1UserSignInWithBody_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignInWithBody_Call) RunAndReturn(run func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostAdminV1UserSignInWithBody_Call {
	_c.Call.Return(run)
	return _c
}

// PostAdminV1UserSignUp provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientInterface) PostAdminV1UserSignUp(ctx context.Context, body viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, reqEditors ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostAdminV1UserSignUp")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostAdminV1UserSignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAdminV1UserSignUp'
type ClientInterface_PostAdminV1UserSignUp_Call struct {
	*mock.Call
}

// PostAdminV1UserSignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - body viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody
//   - reqEditors ...viewsLUadminUuser.RequestEditorFn
func (_e *ClientInterface_Expecter) PostAdminV1UserSignUp(ctx interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostAdminV1UserSignUp_Call {
	return &ClientInterface_PostAdminV1UserSignUp_Call{Call: _e.mock.On("PostAdminV1UserSignUp",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostAdminV1UserSignUp_Call) Run(run func(ctx context.Context, body viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, reqEditors ...viewsLUadminUuser.RequestEditorFn)) *ClientInterface_PostAdminV1UserSignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viewsLUadminUuser.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(viewsLUadminUuser.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignUp_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostAdminV1UserSignUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignUp_Call) RunAndReturn(run func(context.Context, viewsLUadminUuser.PostAdminV1UserSignUpJSONRequestBody, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostAdminV1UserSignUp_Call {
	_c.Call.Return(run)
	return _c
}

// PostAdminV1UserSignUpWithBody provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientInterface) PostAdminV1UserSignUpWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostAdminV1UserSignUpWithBody")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_PostAdminV1UserSignUpWithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAdminV1UserSignUpWithBody'
type ClientInterface_PostAdminV1UserSignUpWithBody_Call struct {
	*mock.Call
}

// PostAdminV1UserSignUpWithBody is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...viewsLUadminUuser.RequestEditorFn
func (_e *ClientInterface_Expecter) PostAdminV1UserSignUpWithBody(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *ClientInterface_PostAdminV1UserSignUpWithBody_Call {
	return &ClientInterface_PostAdminV1UserSignUpWithBody_Call{Call: _e.mock.On("PostAdminV1UserSignUpWithBody",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *ClientInterface_PostAdminV1UserSignUpWithBody_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...viewsLUadminUuser.RequestEditorFn)) *ClientInterface_PostAdminV1UserSignUpWithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]viewsLUadminUuser.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(viewsLUadminUuser.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignUpWithBody_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_PostAdminV1UserSignUpWithBody_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_PostAdminV1UserSignUpWithBody_Call) RunAndReturn(run func(context.Context, string, io.Reader, ...viewsLUadminUuser.RequestEditorFn) (*http.Response, error)) *ClientInterface_PostAdminV1UserSignUpWithBody_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
