// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// PostCustomerV1OrderCustomerSignInResponseObject is an autogenerated mock type for the PostCustomerV1OrderCustomerSignInResponseObject type
type PostCustomerV1OrderCustomerSignInResponseObject struct {
	mock.Mock
}

type PostCustomerV1OrderCustomerSignInResponseObject_Expecter struct {
	mock *mock.Mock
}

func (_m *PostCustomerV1OrderCustomerSignInResponseObject) EXPECT() *PostCustomerV1OrderCustomerSignInResponseObject_Expecter {
	return &PostCustomerV1OrderCustomerSignInResponseObject_Expecter{mock: &_m.Mock}
}

// VisitPostCustomerV1OrderCustomerSignInResponse provides a mock function with given fields: w
func (_m *PostCustomerV1OrderCustomerSignInResponseObject) VisitPostCustomerV1OrderCustomerSignInResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitPostCustomerV1OrderCustomerSignInResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitPostCustomerV1OrderCustomerSignInResponse'
type PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call struct {
	*mock.Call
}

// VisitPostCustomerV1OrderCustomerSignInResponse is a helper method to define mock.On call
//   - w http.ResponseWriter
func (_e *PostCustomerV1OrderCustomerSignInResponseObject_Expecter) VisitPostCustomerV1OrderCustomerSignInResponse(w interface{}) *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call {
	return &PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call{Call: _e.mock.On("VisitPostCustomerV1OrderCustomerSignInResponse", w)}
}

func (_c *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call) Run(run func(w http.ResponseWriter)) *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter))
	})
	return _c
}

func (_c *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call) Return(_a0 error) *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call) RunAndReturn(run func(http.ResponseWriter) error) *PostCustomerV1OrderCustomerSignInResponseObject_VisitPostCustomerV1OrderCustomerSignInResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostCustomerV1OrderCustomerSignInResponseObject creates a new instance of PostCustomerV1OrderCustomerSignInResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostCustomerV1OrderCustomerSignInResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostCustomerV1OrderCustomerSignInResponseObject {
	mock := &PostCustomerV1OrderCustomerSignInResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
