/**
 * SmartTable Mobile API
 * API для управления заказами.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CustomerV1OrderCustomerSignInRequest from '../model/CustomerV1OrderCustomerSignInRequest';
import CustomerV1OrderCustomerSignInResponse from '../model/CustomerV1OrderCustomerSignInResponse';
import CustomerV1OrderCustomerSignUpRequest from '../model/CustomerV1OrderCustomerSignUpRequest';
import CustomerV1OrderCustomerSignUpResponse from '../model/CustomerV1OrderCustomerSignUpResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the customerV1SignInPost operation.
     * @callback module:api/DefaultApi~customerV1SignInPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CustomerV1OrderCustomerSignInResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Авторизация пользователя в приложении
     * Авторизует пользователя
     * @param {module:model/CustomerV1OrderCustomerSignInRequest} customerV1OrderCustomerSignInRequest 
     * @param {module:api/DefaultApi~customerV1SignInPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CustomerV1OrderCustomerSignInResponse}
     */
    customerV1SignInPost(customerV1OrderCustomerSignInRequest, callback) {
      let postBody = customerV1OrderCustomerSignInRequest;
      // verify the required parameter 'customerV1OrderCustomerSignInRequest' is set
      if (customerV1OrderCustomerSignInRequest === undefined || customerV1OrderCustomerSignInRequest === null) {
        throw new Error("Missing the required parameter 'customerV1OrderCustomerSignInRequest' when calling customerV1SignInPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CustomerV1OrderCustomerSignInResponse;
      return this.apiClient.callApi(
        '/customer/v1/sign-in', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the customerV1SignUpPost operation.
     * @callback module:api/DefaultApi~customerV1SignUpPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CustomerV1OrderCustomerSignUpResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Регистрация пользователя в приложении
     * Регистрирует пользователя
     * @param {module:model/CustomerV1OrderCustomerSignUpRequest} customerV1OrderCustomerSignUpRequest 
     * @param {module:api/DefaultApi~customerV1SignUpPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CustomerV1OrderCustomerSignUpResponse}
     */
    customerV1SignUpPost(customerV1OrderCustomerSignUpRequest, callback) {
      let postBody = customerV1OrderCustomerSignUpRequest;
      // verify the required parameter 'customerV1OrderCustomerSignUpRequest' is set
      if (customerV1OrderCustomerSignUpRequest === undefined || customerV1OrderCustomerSignUpRequest === null) {
        throw new Error("Missing the required parameter 'customerV1OrderCustomerSignUpRequest' when calling customerV1SignUpPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CustomerV1OrderCustomerSignUpResponse;
      return this.apiClient.callApi(
        '/customer/v1/sign-up', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
