name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/go.yml'
  pull_request:
    branches: ["main"]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.github/workflows/go.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            backend/smart-table/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          cd backend/smart-table
          go mod tidy

      - name: Check if Go files changed
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.go
            go.mod
            go.sum
            Makefile

      - name: Run code generation
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd backend/smart-table
          make gen

      - name: Build
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd backend/smart-table/build/services/smart-table
          go mod tidy
          go build -v -o build/bin ./...

      - name: Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd backend/smart-table
          go run github.com/golangci/golangci-lint/cmd/golangci-lint run --config .golangci.yaml

      - name: Test
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd backend/smart-table
          go test -v -race -coverpkg=./... ./...
